config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'my_devise/registrations',
    sessions: 'my_devise/sessions',
    omniauth_callbacks: 'my_devise/omniauth_callbacks'
  }

  devise_scope :user do
    get 'change_password', to: 'my_devise/registrations#change_password'
    post 'change_password', to: 'my_devise/registrations#update_password'
  end

  root 'projects#index'

  get 'places_navigation', to: 'places#navigation'

  resources :reviews, only: [:index, :create]

  namespace :manage do
    root 'projects#index'
    resources :projects
  end

  resources :projects, only: [:show] do
    get 'download', on: :member
    get 'download_counter', on: :member
    resources :places
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :places, dependent: :destroy
  has_many :original_places, dependent: :destroy
  has_attached_file :image,
    default_url: '/images/missing.png',
    styles: { :small => '100x100^', :medium => "400x200#",  original: { processors: [:project_image_processor] } }

  validates :title, :place_height, :place_width, :width, :height, presence: true
  validates :image, attachment_presence: true
  validates_attachment_content_type :image,
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  include Zlib
  include ProjectObserving
  include CommonMethods
  include Rails.application.routes.url_helpers

  class << self
    attr_reader :max_width, :max_height
  end
  @max_width, @max_height = 1600, 1300

  def generate_empty_table_html
    view = get_action_view
    html_string = view.render partial: 'manage/projects/empty_table',
      layout: false, locals: { project: self }

    write_deflated_html html_string
  end

  def inflated_html
    Inflate.inflate(html)
  end

  def normalize_friendly_id(input)
   input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  # work on sidekiq
  def compile_with_place(place)
    project_img = rmagick_image
    place_img = place.rmagick_image

    place_img.resize!(place_width, place_height, Magick::LanczosFilter, 1.0)
    project_img.composite!(place_img, place_width * place.x, place_height * place.y, Magick::OverCompositeOp)

    project_img.write(image.path)
    image.reprocess! # (:small) full image decreases in size

    html_compile_with_place(place)
  end

  def to_s
    title
  end

  def html_compile_with_place(place)
    doc = Nokogiri::HTML(inflated_html)

    link = doc.css(".js-table .row_project:nth-child(#{place.y + 1}) .column_project:nth-child(#{place.x + 1}) a")[0]
    link['class'] = 'ajax-place_show'
    link['href'] = project_place_path(self.slug, place.id, x: place.x, y: place.y)

    write_deflated_html(doc.to_html)
  end

  def total_places_count
    places_in_x * places_in_y
  end

  private
  def write_deflated_html(html_string)
    update_attribute(:html, Deflate.deflate(html_string))
  end

  def rmagick_image
    @rmagick_image ||= Magick::Image.read(image.path)[0]
  end
end

# has a project_observer!

# == Schema Information
#
# Table name: projects
#
#  id                 :integer          not null, primary key
#  title              :string
#  html               :binary
#  height             :integer
#  width              :integer
#  place_height       :integer
#  place_width        :integer
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  places_in_y        :integer
#  places_in_x        :integer
#  slug               :string
#  description        :text
#  download_count     :integer          default(0)
#  places_count       :integer          default(0)
#

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :find_projects, only: [:show]

  def index
    raise 'Нет проектов' if Project.none?
    redirect_to project_path(Project.select('slug').first.slug)
  end

  def download_counter
    @project.download_count += 1
    @project.save
    render json: {} and return
  end

  def download
    layout_var = request.xhr? ? 'modal1' : 'col-sm-5'
    render :download, layout: layout_var
  end

  private
  def find_projects
    @projects = Project.all
  end
end

app/views/projects/_projects_navigation.html.erb
<div id='projects_list'>
  <div class='row'>

    <% @projects.each do |project| %>
      <div class='col-project_wrapper col-xs-6 col-sm-4 col-md-3 col-lg-3'>
        <div class='project_item <%= 'active' if @project.eql?(project) %>'>
          <%= link_to (@project.eql?(project) ? 'javascript:void(0)' : project_path(project)) do %>

            <div class='project_title'><p><%= project.title %></p></div>

            <div class='image_wrapper' style='background-image: url(<%= project.image(:medium) %>)'>
              <span class='complete_info'><%= "#{project.places.size}/#{project.total_places_count}" %></span>
            </div>

          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/download.html.erb
<div class='download_project'>

  <div class='info'>
    <h4 class='text-center'>Скачать изображение проекта "<%= @project.title %>"</h4>

    <div class='text-center'>
      <%= image_tag @project.image.url(:small), class: 'margin-tb-15px' %>
    </div>

    <p class='lighter_border_top padding-top-15px'>
      Размеры проекта -
      <%= @project.places_in_x * @project.place_width %>px X <%= @project.places_in_y * @project.place_height %>px.
    </p>

    <p>
      Размеры каждой ячейки -
      <%= @project.place_width %>px X <%= @project.place_height %>px.
    </p>

    <p>
      Ячеек по горизонтали -
      <%= @project.places_in_x %>
    </p>

    <p>
      Ячеек по вертикали -
      <%= @project.places_in_y %>
    </p>

    <p>
      Завершено -
      <%= @project.places.size %> / <%= @project.total_places_count %> (завершённых ячеек / общее количество ячеек)
    </p>

    <% unless @project.download_count.zero? %>
      <p>
        Изображение скачано <%= I18n.t 'helpers.project.download_count',count: @project.download_count %>
      </p>
    <% end %>
  </div>

  <div class='form-actions text-center with-back'>
    <div class='back'></div>
    <%= link_to 'Скачать', @project.image.url,
      download: @project.slug,
      data: {
        url: download_counter_project_path(@project)
      },
      class: 'js-download_counter button button_green close_modals button_large_green button_long' %>
  </div>
</div>

app/views/projects/show.html.erb
<div id='project_show'>
  <div id='title_and_description' class='container'>

    <div id='page_title'>
      <h1><%= @project.title %></h1>
    </div>

    <div class='margin-bottom-5px'>
      <span class='opacity_0_5'>Скачано <%= I18n.t 'helpers.project.download_count',count: @project.download_count %>.</span>
      <span class='complete_info opacity_0_5'>Завершено - <%= "#{@project.places.size}/#{@project.total_places_count}" %></span>
    </div>

    <%= link_to 'скачать', download_project_path(@project), remote: true, class: 'js-remote_modal button button_green' %>

    <div class='jssocials_project'
      data-url='<%= request.original_url %>'
      data-text='<%= "#@project - #{Settings.app.name}" %>'>
    </div>

    <div id='project_description'>
      <%= @project.description %>
    </div>
  </div>

  <div class='js-project_wrapper'>
    <%= @project.inflated_html.html_safe %>
  </div>

  <div class='container height-0'>
    <div class='jssocials_project pull-right'
      data-url='<%= request.original_url %>'
      data-text='<%= "#@project - #{Settings.app.name}" %>'>
    </div>
  </div>

  <div class='container' id='other_projects'>
    <h2>Все проекты</h2>
     <%= render partial: 'projects_navigation' %>
  </div>

</div>

<div class='hidden js-some-infos channel-places' data-project-slug='<%= @project.slug %>'></div>