config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'my_devise/registrations',
    sessions: 'my_devise/sessions',
    omniauth_callbacks: 'my_devise/omniauth_callbacks'
  }

  devise_scope :user do
    get 'change_password', to: 'my_devise/registrations#change_password'
    post 'change_password', to: 'my_devise/registrations#update_password'
  end

  root 'projects#index'

  get 'places_navigation', to: 'places#navigation'

  resources :reviews, only: [:index, :create]

  namespace :manage do
    root 'projects#index'
    resources :projects
  end

  resources :projects, only: [:show] do
    get 'download', on: :member
    get 'download_counter', on: :member
    resources :places
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :resolve_layout

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => 'Не хватает прав для выполнения этого действия'
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name, :crop_x, :crop_y, :crop_height, :crop_width])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name, :crop_x, :crop_y, :crop_height, :crop_width])
  end

  def resolve_layout
    devise_controller? ? 'col-sm-5' : 'application'
  end

  def current_ability
    Ability.new(current_user, controller_namespace)
  end

  def controller_namespace
    controller_name_segments = params[:controller].split('/')
    controller_name_segments.pop
    @controller_namespace = controller_name_segments.join('/').camelize
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_action
    @controller_action ||= [controller.class.name.remove('Controller').downcase, controller.action_name].join('_')
  end

  def og_properties_meta_tags
    case controller_action
    when 'projects_show'
      [
        og_prop('title', "#@project - #{Settings.app.name}"),
        og_prop('type', 'article'),
        og_prop('image', @project.image.url(:medium)),
        og_prop('description', @project.description.truncate(100))
      ].join
    else
      [
        og_prop('title', Settings.app.name),
        og_prop('type', 'article'),
        og_prop('image', asset_path('logotype.png')),
        og_prop('description', I18n.t('app.og_description'))
      ].join
    end.html_safe
  end

  def title_text
    case controller_action
    when 'projects_show'
      "#@project - #{Settings.app.name}"
    else
      Settings.app.name
    end
  end

  def og_prop(name, into)
    content_tag(:meta, nil, property: "og:#{name}", content: into)
  end
end

app/views/application/_alerts.html.erb
<% if notice %>
  <div class='alert alert-info'>
    <p><%= notice %></p>
  </div>
<% end %>
<% if alert %>
  <div class='alert alert-danger'>
    <p><%= alert %></p>
  </div>
<% end %>

app/views/application/_footer.html.erb
<div id='footer' class='border_top'>
  <div class='container'>
    <div class='row'>

      <div class='col-sm-6 left-col'>
        <div class='jssocials_site'
          data-url='<%= Settings.app.host %>'
          data-text='<%= I18n.t('app.jssocials_description') %>'>
        </div>
      </div>

      <div class='col-sm-6 right-col'>
        <div class='footer_info'>
          <p>
            <%= link_to Settings.app.link_text, root_path %> |
            <%= link_to 'Обратная связь', reviews_path %> |
            2017
          </p>
        </div>
      </div>

    </div>
  </div>

  <div class='back_footer'></div>
  <div class='dark_layer'></div>
</div>

app/views/application/_header.html.erb
<div id='header' class='border_bottom'>
  <div class='back_head'></div>
  <div class='dark_layer'></div>

  <%= link_to root_path do %>
    <div id='logotype'></div>
  <% end %>

  <% if user_signed_in? %>
    <div id='users_info'>
      <div id='users_avatar'>
        <%= image_tag current_user.avatar.url(:medium), size: '70x70' %>
      </div>
      <div id='users_email' class='opacity_0_8'>
        <%= current_user.name %>
      </div>
    </div>
  <% end %>

  <div id='top_menu'>
    <%= link_to root_path do %>
      Главная страница
    <% end %>
    <%= link_to reviews_path do %>
      Обратная связь
    <% end %>
  </div>

  <div id='header_menu'>
    <%= render partial: 'application/menu' %>
  </div>
</div>

app/views/application/_manage_header.html.erb
<div id='manage_header'>
  <%= link_to 'Проекты', manage_projects_path %>
  <%= link_to 'Новый проект', new_manage_project_path %>
</div>

app/views/application/_menu.html.erb
<nav class='large'>
  <ul class='nested_menu true_menu'>
    <% if user_signed_in? %>

      <% if @project&.persisted? && can?(:edit, Project) %>
        <li>
          <a class='child-list-link' href='javascript:void(0)'>Управление проектом</a>

          <ul class='child-list'>

            <li>
              <%= link_to 'В админке', manage_project_path(@project) %>
            </li>

            <li>
              <%= link_to 'В публичке', project_path(@project) %>
            </li>

            <li>
              <%= link_to edit_manage_project_path(@project) do %>
                <span>Редактировать</span>
                <span class='glyphicon glyphicon-pencil'></span>
              <% end %>
            </li>

            <li>
              <%= link_to manage_project_path(@project), method: :delete, data: { confirm: 'Ведаешь что творишь?' } do %>
                <span>Удалить</span>
                <span class='glyphicon glyphicon-trash'></span>
              <% end %>
            </li>

          </ul>
        </li>
      <% end %>

      <% if current_user.admin? %>
        <li>
          <%= link_to 'Админка', manage_root_path %>
        </li>
      <% end %>

      <li>
        <%= link_to 'Аккаунт', edit_user_registration_path %>
      </li>

      <li>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
      </li>

    <% else %>
      <li>
        <%= link_to 'Войти', new_user_session_path, remote: true, class: 'js-remote_modal' %>
      </li>

      <li>
        <%= link_to 'Зарегистрироваться', new_user_registration_path %>
      </li>
    <% end %>
  </ul>
</nav>